[[themes]]
name = "matugen_dynamic"

[themes.palette]
background      = "{{ colors.surface.default.hex}}"
foreground      = "{{ colors.on_surface.default.hex}}"

black           = "{{ colors.surface_variant.default.hex}}"
red             = "{{ colors.error.default.hex}}"
green           = "{{ colors.tertiary.default.hex}}"
yellow          = "{{ colors.primary.default.hex}}"
blue            = "{{ colors.secondary.default.hex}}"
magenta         = "{{ colors.secondary_container.default.hex}}"
cyan            = "{{ colors.tertiary_container.default.hex}}"
white           = "{{ colors.on_surface_variant.default.hex}}"

bright_black    = "{{ colors.outline.default.hex}}"
bright_red      = "{{ colors.error_container.default.hex}}"
bright_green    = "{{ colors.tertiary_container.default.hex}}"
bright_yellow   = "{{ colors.surface_container_highest.default.hex}}"
bright_blue     = "{{ colors.primary_container.default.hex}}"
bright_magenta  = "{{ colors.inverse_surface.default.hex}}"
bright_cyan     = "{{ colors.inverse_primary.default.hex}}"
bright_white    = "{{ colors.background.default.hex}}"
